### ISSUE TITLE
License not found for [@esrecurse 4.3.0]

### ISSUE THREAD

**Issue by RohaitKS** [estools/esrecurse#24]
Hello Everyone, How can I find the license file of [@esrecurse 4.3.0] . Master license is available, but I am looking for the specific these one.

**Comment by RReverser** [comment]
Same as in other places you submitted issue - it's unclear where you've been looking, but it's pretty easy to find right in the same repo or npm package.

**Comment by RohaitKS** [comment]
HI RReverser,

Thank you for the prompt response. I want to find license file here:  https://github.com/estools/esrecurse . 
I am looking for the specifically ' esrecurse 4.3.0 ' not master license  file. A screenshot is attached below for the further reference. Kindly help me in this regard


**Master license file is available but esrecurse  is not available.** 
![image](https://user-images.githubusercontent.com/105201101/194052874-f9f45cf6-5449-464d-9f2f-831873ee352e.png)


**Looking for below license file:**
![image](https://user-images.githubusercontent.com/105201101/194053071-49d5c8ab-c0f5-44f4-adf2-b9f801e65943.png)


I hope, it is cleared for you now

**Comment by RReverser** [comment]
No it's not. Like with acorn issue, I have no idea why you're trying to look for branch called "esrecurse" in an esrecurse repo. The license is right there among files.

**Comment by michaelficarra** [comment]
https://github.com/estools/esrecurse/blob/v4.3.0/package.json#L41
