### ISSUE TITLE
RangeError: Maximum call stack size exceeded  

### ISSUE THREAD

**Issue by stkrzysiak** [estools/esrecurse#7]
Hi, 
I was trying to run the tests for react-router and I run into a call stack issue.  Is this the proper place to raise this concern or should I do it on react-router's issue queue?
My local environment(Mac) looks like this: 
➜  react-router git:(master) node --version; npm --version; git rev-parse HEAD;
v5.1.0
3.5.0
d92d83d268e6c356a1cf996d784ca561009d6b8c

[esrecurse-callstack.txt](https://github.com/estools/esrecurse/files/46712/esrecurse-callstack.txt)

Thanks!

**Comment by nzakas** [comment]
See https://github.com/eslint/eslint/issues/4485

tl;dr this is an issue with babel-eslint

**Comment by stkrzysiak** [comment]
Great, thank you @nzakas !
